version: "3.8"

services:
  velox-vm-image:
    build:
      context: ../
      dockerfile: .docker.dev/Dockerfile.dev
    container_name: vm
    restart: always
    ports:
      - 9000:9000
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=w3schools
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=w3schools
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ../database/sample.sql:/docker-entrypoint-initdb.d/sample.sql

volumes:
  mysql_data:
